<?xml version="1.0" encoding="utf-8"?>
<Database Name="exdb" Class="exdb" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Accounts" Member="Accounts">
    <Type Name="Account">
      <Column Name="ID"
              Type="System.Int32"
              DbType="Int IDENTITY NOT NULL"
              IsPrimaryKey="true"
              IsDbGenerated="true"
              CanBeNull="false" />
      
      <Column Name="Name"
              Type="System.String"
              DbType="VarChar(50) NOT NULL"
              CanBeNull="false" />
      
      <Column Name="Password"
              Type="System.String"
              DbType="VarChar(50) NOT NULL"
              CanBeNull="false" />
      
      <Column Name="Balance"
              Type="System.Int32"
              DbType="Int NOT NULL"
              CanBeNull="false" />
    </Type>
  </Table>
</Database>